apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaifa-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaifa
  template:
    metadata:
      labels:
        app: kaifa
    spec:
      containers:
        - name: kaifa
          image: nazmul4532brainstation/kaifa-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: LIMIT
              value: "500"
            - name: MONGODB_URI
              value: "mongodb://nazmulhossain:LMuv3YImXfSmE6Eq@kaifa-mongo-service.mongodb.svc.cluster.local:27017/kaifa?authSource=admin"
            - name: NODE_ENV
              value: "production"

---
apiVersion: v1
kind: Service
metadata:
  name: kaifa-service
spec:
  selector:
    app: kaifa
  ports:
    - port: 80
      targetPort: 3000

